---
token: 'token' # Your bot's login token, keep this safe!
commandPrefix: a@ # Your bot's prefix to use for commands.
commandEditableDuration: 30 # The amount of time before a command cannot be edited. (Only ping supports this right now.)
nonCommandEditable: false # Whether commands can be edited after they have been executed.
unknownCommandResponse: false # Whether to tell the user if a command is invalid and provide a possible match.
invite: http://discord.gg/8QebTbk # The server invite to the support server.
joinMessageBlacklist: # The blacklist of servers to not send a join message to when joining a new server.
  - '110373943822540800' # Discord Bots
  - '264445053596991498' # Discord Bots List
