---
- name: cat16#0725
  id: '217797734982352896'
  info: Helped with *a lot* of issues and questions I had.
  github: cat16

- name: Michael | ASIANBOI#4150
  id: '171319044715053057'
  info: Offered suggestions and feedback.
  github: mcao

- name: Ariathe#4163
  id: '325828052422492162'
  info: Designed the avatar for AceBot.

- name: Thatguychris#3998
  id: '158397118611062785'
  info: Did the web scraping for the old version of `discordstatus`

- name: DarthAbhinav#6579
  id: '374439777136541697'
  info: Tests literally everything.
